Milly:
  CrudUI:
    defaultTheme: 'neos'

Neos:
  Neos:
    fusion:
      autoInclude:
        Milly.CrudUI: true
  Fusion:
    defaultContext:
      'Milly.CrudUI': Milly\CrudUI\Eel\Helper\CrudUIHelper
      'Milly.Object': Milly\CrudUI\Eel\Helper\ObjectHelper
      'DateInterval': Milly\CrudUI\Eel\Helper\DateIntervalHelper
