Milly:
  CrudForms:
    defaultTheme: 'neos'

Neos:
  Neos:
    fusion:
      autoInclude:
        Milly.CrudForms: true
  Fusion:
    defaultContext:
      'Milly.CrudForms': Milly\CrudForms\Eel\Helper\CrudFormsHelper
      'Milly.Object': Milly\CrudForms\Eel\Helper\ObjectHelper
      'DateInterval': Milly\CrudForms\Eel\Helper\DateIntervalHelper
