Milly:
  CrudForms:
    themes:
      neos:
        layout:
          container:
            class: "neos-content neos-fluid-container neos-indented"
            header:
              class: ""
            main:
              class: "neos-row-fluid"
              content:
                first:
                  class: 'neos-span6'
                second:
                  class: 'neos-span6'
            footer:
              class: "neos-footer"

        atom:
          actionUi:
            default:
              link:
                class: "neos-button neos-button-primary"
              button:
                class: "neos-button neos-button-primary"
            new:
              link:
                class: ~
            show:
              link:
                class: ""
            edit:
              link:
                class: ~
            exportCsv:
              link:
                class: 'neos-button'
            sorting:
              button:
                class: ~
            delete:
              button:
                class: "neos-button neos-button-danger"
            update:
              button:
                class: ~
            create:
              button:
                class: ~
        propertyEditor:
          textfield:
            class: "neos-span12"
          textarea:
            class: "neos-span12"
          number:
            class: 'neos-span3'
        molecule:
          propertyEditorContainer:
            type: 'Neos.Fusion.Form:Neos.BackendModule.FieldContainer'
          pagination:
            link:
              class: 'neos-button'
        template:
          index:
            main:
              content:
                first:
                  narrowClass: 'neos-span6'
                  wideClass: 'neos-span12'
            table:
              class: "neos-table"
          edit:
            form:
              class: "neos-control-group"
          new:
            form:
              class: "neos-control-group"
          show:
            table:
              class: "neos-table show"
